# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestScrollView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestScrollView


 	pod ‘AFNetworking’, ‘~>3.1.0’
 	pod 'pop', '~> 1.0.9'
	pod 'Masonry', '~> 1.0.2'

  target 'TestScrollViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestScrollViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
